config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users, only: [:create, :new]

  resource :session, only: [:create, :new, :destroy]

  root to: redirect('/cats')
end

app/views/layouts/_login.html.erb
<!-- action: log_in  -->

<% if action == :log_in %>
<%    url_var = session_url %>
<% else %>
<%    url_var = users_url %>
<% end %>

<form action=" <%= url_var %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_name">Username</label>
  <input type="text" name="user[user_name]" value="">

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="">

  <input type="submit" value="SUBMIT">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>

    <% if current_user %>
    <%    name_of_user = current_user.user_name %>
    <% end %>

    <% if name_of_user %>
      <p> BE GREETED, <%= name_of_user  %>! </p>
      <%= button_to "Logout", :session, method: :delete %>
    <% else %>
      <%= button_to "LOGIN", :new_session, method: :get %>
      <%= button_to "SIGN UP", :new_user, method: :get %>
    <% end %>

  </header>

  <body>
    <%= yield %>
  </body>
</html>